vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        articles_images:
            uri_prefix: /assets/uploads/marques
            upload_destination: '%kernel.project_dir%//assets/uploads/marques'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
